import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius } from '../theme/colors';
// Estilos específicos para HomeScreen y sus componentes relacionados
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: spacing.lg,
    paddingBottom: 100,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoSquare: {
    width: 35,
    height: 35,
    backgroundColor: '#facc15',
    borderRadius: borderRadius.cardSm,
    marginRight: spacing.sm,
  },
  brandText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  historyCircle: {
    padding: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: borderRadius.input,
  },
  motoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: borderRadius.cardLg,
    marginBottom: spacing.lg,
  },
  motoActiveBorder: {
    borderColor: colors.motoActive,
    borderWidth: 1,
  },
  motoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  subText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  monitoringContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  monitoringText: {
    fontSize: 11,
    color: colors.motoActive,
    fontWeight: '600',
  },
  instructionContainer: {
    alignItems: 'center',
    marginBottom: spacing.lg,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: borderRadius.cardLg,
    borderColor: colors.border,
    borderWidth: 1,
  },
  mainInstruction: {
    fontSize: 26,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  subInstruction: {
    fontSize: 16,
    color: colors.textSecondary,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  voiceCard: {
    backgroundColor: '#112942',
    borderRadius: borderRadius.cardLg || 35,
    paddingVertical: spacing.xl,
    alignItems: 'center',
  },
  micCircle: {
    backgroundColor: colors.moderate,
    padding: spacing.md + 4,
    borderRadius: 40,
    marginBottom: spacing.md,
  },
  voiceTitle: {
    color: colors.surface,
    fontSize: 22,
    fontWeight: '700',
    marginBottom: spacing.md,
  },
  audioVisualizer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 30,
    gap: 4,
    marginBottom: spacing.md,
  },
  audioBar: {
    width: 3,
    backgroundColor: colors.textSecondary,
    borderRadius: 2,
  },
  voiceSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  dividerText: {
    textAlign: 'center',
    color: colors.textSecondary,
    marginVertical: spacing.md,
  },
  textAreaWrapper: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.cardLg,
    padding: spacing.md,
    minHeight: 120,
    borderWidth: 1,
    borderColor: colors.border,
    position: 'relative',
    overflow: 'hidden',
  },
  orangeAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 6,
    backgroundColor: colors.moderate,
  },
  textArea: {
    fontSize: 16,
    color: colors.textPrimary,
    textAlignVertical: 'top',
    paddingLeft: spacing.sm,
  },
  charCounter: {
    position: 'absolute',
    bottom: 10,
    right: 15,
    color: colors.textSecondary,
    fontSize: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    letterSpacing: 1,
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  chip: {
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.pill,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipActive: {
    backgroundColor: colors.navy,
    borderColor: colors.navy,
  },
  chipText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  chipTextActive: {
    color: colors.surface,
    fontWeight: '600',
  },
  mainButton: {
    backgroundColor: colors.navy,
    borderRadius: borderRadius.pill,
    height: 60,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  mainButtonText: {
    color: colors.surface,
    fontSize: 18,
    fontWeight: 'bold',
  },
  tabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 70,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingBottom: spacing.sm,
  },
});